#!/bin/sh

. /etc/pydota.conf

start() {
    if [ -f ${pydota_cron} ]; then
         cat ${pydota_cron} | sed '/py_dota_collect.sh/d' > ${pydota_cron}_tmp
         mv ${pydota_cron}_tmp ${pydota_cron}
         echo "30 * * * * junjian ${pydota_path}/service/py_dota_collect.sh" >> ${pydota_cron}
    else
         echo "30 * * * * junjian ${pydota_path}/service/py_dota_collect.sh" >> ${pydota_cron}
    fi
    /etc/init.d/crond restart
 }

 stop() {
    if [ -f ${pydota_cron} ]; then
         cat ${pydota_cron} | sed '/py_dota_collect.sh/d' > ${pydota_cron}_tmp
         mv ${pydota_cron}_tmp ${pydota_cron}
    fi
    if [ -f ${pydota_collect_pids} ]; then
        for pid in `cat ${pydota_collect_pids}`;
        do
            kill -9 $pid 1>/dev/null 2>&1
        done
        echo "" > ${pydota_collect_pids}
    fi
    /etc/init.d/crond restart
 }

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop;
        start;
        ;;
esac
